# Generated by Django 4.2.2 on 2023-06-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image',
        ),
    ]
